/* ══════════════════════════════════════
   i18n.js
   ══════════════════════════════════════ */
const LANG = {
  id: { subtitle:'MP4 Optimizer · HD Quality — by D4nzxml',statVid:'Videos',statRate:'Success Rate',statQ:'Kualitas',trust:'Dipercaya Creator • HD Quality Certified',prevHint:'Preview video',selectMode:'Pilih Mode',m1n:'Smart Patch',m1d:'Otomatis deteksi & proses',m1b:'AUTO',m2d:'Optimasi frame timing video',m2b:'ADVANCED',selectMultiplier:'Pilih Multiplier',selectVideo:'Drag & Drop atau Klik',noFile:'Belum ada file dipilih...',statusLabel:'Status Proses',ready:'Siap — pilih video untuk memulai.',patchDownload:'PATCH & DOWNLOAD',warnTitle:'⚠️ Penting',warnText:'Video yang diupload ke TikTok tanpa proses ini akan otomatis dikompresi dan tidak bisa HD.',warnPatchText:'Video tanpa proses akan dikompresi TikTok dan tidak bisa HD.',guideTitle:'Panduan Penggunaan',guideMode1:'⚡ Smart Patch',g1s1t:'Pilih Video',g1s1d:'Tap area upload atau drag & drop file MP4.',g1s2t:'Tap PATCH & DOWNLOAD',g1s2d:'Tool otomatis scan & proses video. File hasil langsung terunduh.',g1s3t:'Upload ke TikTok',g1s3d:'Buka tiktok.com/upload. Upload file hasil — jangan upload file aslinya.',guideMode4:'🚀 Speed Booster',g4s1t:'Pilih Mode Speed Booster + Multiplier',g4s1d:'Pilih x2 (recommended) atau x4. Gunakan video 60fps.',g4s2t:'Tap PATCH & DOWNLOAD',g4s2d:'Jangan gunakan sound TikTok setelah upload.',tipText:'Verifikasi hasil dengan MediaInfo → bagian General → pastikan metadata video sudah teroptimasi.',socialLabel:'Sosial Media & Kontak',navPatcher:'Patcher',navGuide:'Panduan',navInfo:'Info',resTitle:'Berhasil!',resSub:'Video siap diupload ke TikTok',rFile:'Nama File',rTime:'Waktu Proses',rBefore:'Sebelum',rAfter:'Sesudah' },
  en: { subtitle:'MP4 Optimizer · HD Quality — by D4nzxml',statVid:'Videos',statRate:'Success Rate',statQ:'Quality',trust:'Trusted by Creators • HD Quality Certified',prevHint:'Video preview',selectMode:'Select Mode',m1n:'Smart Patch',m1d:'Auto detect & process',m1b:'AUTO',m2d:'Optimize video frame timing',m2b:'ADVANCED',selectMultiplier:'Select Multiplier',selectVideo:'Drag & Drop or Click',noFile:'No file selected...',statusLabel:'Process Status',ready:'Ready — select a video to begin.',patchDownload:'PATCH & DOWNLOAD',warnTitle:'⚠️ Important',warnText:'Videos uploaded to TikTok without processing will be compressed and cannot display in HD.',warnPatchText:'Videos without processing will be compressed by TikTok and cannot be HD.',guideTitle:'User Guide',guideMode1:'⚡ Smart Patch',g1s1t:'Select Video',g1s1d:'Tap upload area or drag & drop MP4 file.',g1s2t:'Tap PATCH & DOWNLOAD',g1s2d:'Tool auto-scans & processes video. File downloads immediately.',g1s3t:'Upload to TikTok',g1s3d:'Open tiktok.com/upload. Upload the result — not the original.',guideMode4:'🚀 Speed Booster',g4s1t:'Select Speed Booster Mode + Multiplier',g4s1d:'Choose x2 (recommended) or x4. Use 60fps video.',g4s2t:'Tap PATCH & DOWNLOAD',g4s2d:'Do not use TikTok sounds after upload.',tipText:'Verify with MediaInfo → General section → confirm video metadata is optimized.',socialLabel:'Social Media & Contact',navPatcher:'Patcher',navGuide:'Guide',navInfo:'Info',resTitle:'Success!',resSub:'Video ready to upload to TikTok',rFile:'File Name',rTime:'Process Time',rBefore:'Before',rAfter:'After' }
};
let currentLang = localStorage.getItem('d4nz_lang') || 'id';
function setLang(l) {
  currentLang = l; localStorage.setItem('d4nz_lang', l);
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.dataset.lang === l));
  document.querySelectorAll('[data-i18n]').forEach(el => { const k = el.dataset.i18n; if (LANG[l][k] !== undefined && el.tagName !== 'INPUT') el.textContent = LANG[l][k]; });
  if (!selectedFile) { const d = document.getElementById('fileDisp'); if (d) d.textContent = LANG[l].noFile; }
}
